server:
  servlet:
    context-path: /${spring.application.name}

knife4j:
  enable: true

spring:
  application:
    name: noname
  #视图热部署
  thymeleaf:
    cache: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://124.220.33.168:3306/${spring.application.name}
    username: root
    password: ianunei.cn
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  messages:
    use-code-as-default-message: true
  # knife4j内置的Springfox版本使用的路径匹配是基于AntPathMatcher的, 而Spring Boot 2.6.X使用的是PathPatternMatcher, 所以需要指定一下
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
  file:
    name: /myfile/service/ianunei/${spring.application.name}/logs/${spring.application.name}.log
